version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - './data:/data/db'
  todo:
    container_name: todo
    build:
      context: .
      dockerfile: ${DOCKERFILE:-todo.dockerfile}
    env_file:
      - /todo-api/.env
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
      - user
  user:
    container_name: user
    build:
      context: .
      dockerfile: ${DOCKERFILE:-user.dockerfile}
    env_file:
      - /user-api/.env
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
volumes:
  mongodb_data: